name: utils
channels:
  - pytorch-lts
  - conda-forge
  - anaconda
dependencies:
  - python=3.7.*
  - pytorch=1.8.2
  - torchvision=0.9.2
  - cudatoolkit=10.1
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - pandas
      - onnx==1.12.0
      - onnxruntime-gpu==1.4
      - git+https://github.com/TylerYep/torchinfo.git
